USE oric_portal;

CREATE TABLE IF NOT EXISTS portal_state (
  state_key VARCHAR(120) PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
