import { motion } from "framer-motion";
import { FaLightbulb, FaEye, FaBullseye, FaUsers, FaRocket } from "react-icons/fa";
import logo from '../assets/logo/goal.png';

const WhoWeAre = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="min-h-screen bg-gradient-to-b from-[#0A192F] to-[#112240] text-white py-12 px-4 sm:px-6 lg:px-8 mt-20"
    >
      <div className="max-w-6xl mx-auto">
        {/* Header Section */}
        <div className="text-center mb-16">
          <motion.h1 
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent"
          >
            Who We Are?
          </motion.h1>
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="w-24 h-1 bg-cyan-400 mx-auto mb-6"
          />
        </div>

        {/* About Section */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="mb-16"
        >
          <div className="flex items-center mb-6">
            <div className="bg-gradient-to-r from-cyan-500 to-blue-600 p-3 rounded-lg mr-4">
              <FaLightbulb className="text-2xl" />
            </div>
            <h2 className="text-3xl font-bold">About Us</h2>
          </div>
          
          <div className="bg-[#0A192F]/70 backdrop-blur-sm rounded-xl border border-cyan-500/20 p-6 md:p-8 shadow-lg space-y-4">
            <p>
              MUET University of Engineering and Technology with the vision of becoming the first entrepreneurial university in the region developed its Business Incubation Centre in 2015. BIC is an initiative to create an ecosystem for incubating Tech Start-Ups, particularly in the field of engineering.
            </p>
            <p>
              It aims to assist engineering students shape their innovative idea into revenue generating business model whilst giving opportunities to commercial partners for investing in businesses that have potential to lead the new industrial trends.
            </p>
            <p>
              BIC-MUET is mainly focused on innovative ideas and engineering projects, which generate far more value than other categories of startups. With most wealth generated by technology companies as of today, BIC seeks to improve Pakistan's economic standing by leading future tech startups within this country.
            </p>
          </div>
        </motion.section>

        {/* Vision & Mission */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
          {/* Vision */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            className="bg-[#0A192F]/70 backdrop-blur-sm rounded-xl border border-cyan-500/20 p-6 shadow-lg"
          >
            <div className="flex items-center mb-4">
              <div className="bg-cyan-500/10 p-2 rounded-lg mr-3">
                <FaEye className="text-cyan-400 text-xl" />
              </div>
              <h3 className="text-2xl font-bold">Vision</h3>
            </div>
            <p className="text-blue-200">
              To create a vibrant and sustainable ecosystem on University campus for nurturing and enrichment of Creativity, Innovation and Entrepreneurship.
            </p>
          </motion.div>

          {/* Mission */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 }}
            className="bg-[#0A192F]/70 backdrop-blur-sm rounded-xl border border-cyan-500/20 p-6 shadow-lg"
          >
            <div className="flex items-center mb-4">
              <div className="bg-cyan-500/10 p-2 rounded-lg mr-3">
                <FaRocket className="text-cyan-400 text-xl" />
              </div>
              <h3 className="text-2xl font-bold">Mission</h3>
            </div>
            <p className="text-blue-200">
              We are committed to nurture and support creativity, innovation and entrepreneurship amongst students, faculty members and other aspirants for establishment and growth of technology businesses to meet the social obligations and economic growth of our communities.
            </p>
          </motion.div>
        </div>

        {/* Goals Section */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="mb-16"
        >
          <div className="flex items-center mb-6">
            <div className="bg-gradient-to-r from-cyan-500 to-blue-600 p-3 rounded-lg mr-4">
              <FaBullseye className="text-2xl" />
            </div>
            <h2 className="text-3xl font-bold">Our Goals</h2>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="bg-[#0A192F]/70 backdrop-blur-sm rounded-xl border border-cyan-500/20 p-6 shadow-lg">
              <h3 className="text-xl font-bold mb-3 text-cyan-400">BIC Goal</h3>
              <p className="mb-4 text-blue-200">
                Being a business incubator, BIC's main goal is to produce successful firms that will leave the program financially viable and freestanding. BIC graduates have the potential to create jobs, revitalize neighborhoods, commercialize new technologies, and strengthen local and national economies.
              </p>
              
          
            </div>

            {/* Animated Goal Image */}
            <motion.div
              initial={{ scale: 0.95, y: 10 }}
              animate={{ scale: 1, y: 0 }}
              transition={{ 
                duration: 3,
                repeat: Infinity,
                repeatType: "mirror",
                ease: "easeInOut"
              }}
              className="flex items-center justify-center"
            >
              <img 
                src={logo} 
                alt="BIC Goals" 
                className="w-48 h-48 md:w-64 md:h-64 object-contain rounded-lg shadow-lg border-2 border-cyan-400/20 hover:border-cyan-400/40 transition-all"
                />            </motion.div>
          </div>
        </motion.section>

        {/* Advisory Board Details */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
        >
          <div className="bg-[#0A192F]/70 backdrop-blur-sm rounded-xl border border-cyan-500/20 p-6 shadow-lg">
            <div className="flex items-center mb-4">
              <div className="bg-gradient-to-r from-cyan-500 to-blue-600 p-2 rounded-lg mr-3">
                <FaUsers className="text-xl" />
              </div>
              <h3 className="text-2xl font-bold">Advisory Board Members</h3>
            </div>
            <p className="text-blue-200">
              All advisory board members are encouraged to meet with university management and students to discuss latest practices and industrial requirements for developing an entrepreneurial ecosystem.
            </p>
          </div>
        </motion.section>
      </div>
    </motion.div>
  );
};

export default WhoWeAre;